 postgres-jfrog:
    image: postgres:12
    environment:
      POSTGRES_USER: artifactory
      POSTGRES_PASSWORD: artifactory
      POSTGRES_DB: artifactory
    volumes:
      - postgres_jfrog_data:/var/lib/postgresql/data

  # JFrog Artifactory Service
  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:latest
    depends_on:
      - postgres-jfrog
    environment:
      DB_TYPE: postgresql
      DB_HOST: postgres-jfrog
      DB_PORT: 5432
      DB_USER: artifactory
      DB_PASSWORD: artifactory
      DB_URL: jdbc:postgresql://postgres-jfrog:5432/artifactory
    ports:
      - "8081:8081"
    volumes:
      - artifactory_data:/var/opt/jfrog/artifactory

volumes:
  postgres_data:
  sonarqube_data:
  sonarqube_logs:
  postgres_jfrog_data:
  artifactory_data:

